// 'use client'
import "./globals.css";
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/navigation';
import 'swiper/css/thumbs';
import "react-datepicker/dist/react-datepicker.css";
import {Jost, Forum} from "next/font/google";
import Layout from "@/Layout/Layout";

const jost = Jost({
        subsets: ["latin", "cyrillic"],
        weight: ['400', '500', "600", '800'],
        variable: "--font-jost"

    }
);
const forum = Forum({
    subsets: ["latin", "cyrillic"],
    weight: '400',
    variable: "--font-forum"
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    return (
        <html lang="en">
        <body className={`[  ${forum.variable} ,${jost.variable}  ]`}>
        <Layout>
            {children}
        </Layout>
        </body>
        </html>
    )
        ;
}
