// 'use client'
import ReduxProvider from "@/store/ReduxProvider";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/navigation';
import 'swiper/css/thumbs';
import "react-datepicker/dist/react-datepicker.css";
// import "../localization/i18n";
import { Jost ,Forum } from "next/font/google";
// import {QueryClient} from "react-query";

const jost = Jost({
      subsets: ["latin" , "cyrillic"],
weight:['400' , '500' , "600", '800'],
      variable: "jost"

}
);
const forum = Forum({ subsets: ["latin", "cyrillic"] ,
  weight:'400',
  variable: "--font-forum"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const queryClient = new QueryClient();

  return (
      <html lang="en">
      <body className={`[  ${forum.className} ,${jost.className}  ]`}>
      <ReduxProvider>
        {children}
      </ReduxProvider>
      </body>
</html>
)
  ;
}
