import "./globals.css";

import "react-datepicker/dist/react-datepicker.css";
import { Jost, Forum} from "next/font/google";
import Layout from "@/Layout/Layout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const jost = Jost({
        subsets: ["latin", "cyrillic"],
        weight: ['100', '200','400' ,'500' , "600" , "700" , '800' ],
        variable: "--font-jost",
        display:'swap'

    }
);
const forum = Forum({
    subsets: ["latin", "cyrillic"],
    weight: '400',
    variable: "--font-forum",
    display:'swap'
});

export default function RootLayout({children}) {
    return (
        <html lang="en" className={`font-jost ${jost.variable} ${forum.variable}`}>
        <body>
        <Layout>
            {children}
        </Layout>
        </body>
        </html>
    );
}
